# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies for TrackerService
        run: dotnet restore TrackerService/TrackerService.TrackerService.csproj

      - name: Restore dependencies for ReportService
        run: dotnet restore ReportService/ReportService.csproj

      - name: Restore dependencies for GatewayService
        run: dotnet restore APIGatewayService/APIGatewayService.csproj

      - name: Build TrackerService
        run: dotnet build TrackerService/TrackerService.TrackerService.csproj --no-restore

      - name: Build ReportService
        run: dotnet build ReportService/ReportService.csproj --no-restore

      - name: Test TrackerService
        run: dotnet test TrackerService/TrackerService.Tests/TrackerService.Tests.csproj --no-build --verbosity normal
